### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by cantalupo555** [krmanik/anki-arm64#4]
Ubuntu 22.04 - Armbian Gnome - Orange Pi 5

Hi, I couldn't compile Anki, it gives this error.
```
~/anki$ bazel build -k --config opt dist
WARNING: Invoking Bazel in batch mode since it is not invoked from within a workspace (below a directory having a WORKSPACE file).
Extracting Bazel installation...
ERROR: The 'build' command is only supported from within a workspace (below a directory having a WORKSPACE file).
See documentation at https://bazel.build/concepts/build-ref#workspace
```

**Comment by krmanik** [comment]
The build system changed for the latest version of anki. Now ninja is used. If you want to use older version then check if bazel build system used or ninja build system. This can be found from release page of anki.

To build latest anki, three dependency required
- ninja
- nodejs
- protobuf compiler

During build it is download in out folder but it can be changed to used local binary.

The build easy now.
```
git clone --recurse-submodules https://github.com/ankitects/anki.git
cd anki
./run
```

**Comment by cantalupo555** [comment]
@krmanik I already tried, but I got this error:

```
   Compiling backtrace v0.3.67
   Compiling aes v0.7.5
   Compiling zstd v0.11.2+zstd.1.5.2
   Compiling bzip2 v0.4.4
   Compiling pbkdf2 v0.11.0
   Compiling zstd-safe v6.0.2+zstd.1.5.2
   Compiling sha1 v0.10.5
   Compiling zstd v0.12.2+zstd.1.5.2
   Compiling zip v0.6.3
   Compiling bstr v1.1.0
   Compiling snafu v0.7.4
   Compiling same-file v1.0.6
   Compiling which v4.3.0
   Compiling walkdir v2.3.2
   Compiling globset v0.4.10
   Compiling lazy_static v1.4.0
   Compiling maplit v1.0.2
   Compiling tokio-util v0.7.4
   Compiling h2 v0.3.15
   Compiling hyper v0.14.23
   Compiling workspace-hack v0.1.0 (/home/user/anki/tools/workspace-hack)
   Compiling ninja_gen v0.0.0 (/home/user/anki/build/ninja_gen)
   Compiling configure v0.0.0 (/home/user/anki/build/configure)
    Finished dev [unoptimized + debuginfo] target(s) in 46.05s
     Running `out/rust/debug/configure`
[37/73; 9 active; 167.747s] qt/aqt:forms
FAILED: /home/user/anki/out/qt/_aqt/forms/about_qt6.py /home/user/anki/out/qt/_aqt/forms/addcards_qt5.py /home/user/anki/out/qt/_aqt/forms/addcards_qt6.py /home/user/anki/out/qt/_aqt/forms/addfield_qt5.py /home/user/anki/out/qt/_aqt/forms/addfield_qt6.py /home/user/anki/out/qt/_aqt/forms/addmodel_qt5.py /home/user/anki/out/qt/_aqt/forms/addmodel_qt6.py /home/user/anki/out/qt/_aqt/forms/addonconf_qt5.py /home/user/anki/out/qt/_aqt/forms/addonconf_qt6.py /home/user/anki/out/qt/_aqt/forms/addons_qt5.py /home/user/anki/out/qt/_aqt/forms/addons_qt6.py /home/user/anki/out/qt/_aqt/forms/browser_qt5.py /home/user/anki/out/qt/_aqt/forms/browser_qt6.py /home/user/anki/out/qt/_aqt/forms/browserdisp_qt5.py /home/user/anki/out/qt/_aqt/forms/browserdisp_qt6.py /home/user/anki/out/qt/_aqt/forms/browseropts_qt5.py /home/user/anki/out/qt/_aqt/forms/browseropts_qt6.py /home/user/anki/out/qt/_aqt/forms/changemap_qt5.py /home/user/anki/out/qt/_aqt/forms/changemap_qt6.py /home/user/anki/out/qt/_aqt/forms/changemodel_qt5.py /home/user/anki/out/qt/_aqt/forms/changemodel_qt6.py /home/user/anki/out/qt/_aqt/forms/clayout_top_qt5.py /home/user/anki/out/qt/_aqt/forms/clayout_top_qt6.py /home/user/anki/out/qt/_aqt/forms/customstudy_qt5.py /home/user/anki/out/qt/_aqt/forms/customstudy_qt6.py /home/user/anki/out/qt/_aqt/forms/dconf_qt5.py /home/user/anki/out/qt/_aqt/forms/dconf_qt6.py /home/user/anki/out/qt/_aqt/forms/debug_qt5.py /home/user/anki/out/qt/_aqt/forms/debug_qt6.py /home/user/anki/out/qt/_aqt/forms/editaddon_qt5.py /home/user/anki/out/qt/_aqt/forms/editaddon_qt6.py /home/user/anki/out/qt/_aqt/forms/editcurrent_qt5.py /home/user/anki/out/qt/_aqt/forms/editcurrent_qt6.py /home/user/anki/out/qt/_aqt/forms/edithtml_qt5.py /home/user/anki/out/qt/_aqt/forms/edithtml_qt6.py /home/user/anki/out/qt/_aqt/forms/emptycards_qt5.py /home/user/anki/out/qt/_aqt/forms/emptycards_qt6.py /home/user/anki/out/qt/_aqt/forms/exporting_qt5.py /home/user/anki/out/qt/_aqt/forms/exporting_qt6.py /home/user/anki/out/qt/_aqt/forms/fields_qt5.py /home/user/anki/out/qt/_aqt/forms/fields_qt6.py /home/user/anki/out/qt/_aqt/forms/fields_web_qt5.py /home/user/anki/out/qt/_aqt/forms/fields_web_qt6.py /home/user/anki/out/qt/_aqt/forms/filtered_deck_qt5.py /home/user/anki/out/qt/_aqt/forms/filtered_deck_qt6.py /home/user/anki/out/qt/_aqt/forms/finddupes_qt5.py /home/user/anki/out/qt/_aqt/forms/finddupes_qt6.py /home/user/anki/out/qt/_aqt/forms/findreplace_qt5.py /home/user/anki/out/qt/_aqt/forms/findreplace_qt6.py /home/user/anki/out/qt/_aqt/forms/forget_qt5.py /home/user/anki/out/qt/_aqt/forms/forget_qt6.py /home/user/anki/out/qt/_aqt/forms/getaddons_qt5.py /home/user/anki/out/qt/_aqt/forms/getaddons_qt6.py /home/user/anki/out/qt/_aqt/forms/importing_qt5.py /home/user/anki/out/qt/_aqt/forms/importing_qt6.py /home/user/anki/out/qt/_aqt/forms/main_qt5.py /home/user/anki/out/qt/_aqt/forms/main_qt6.py /home/user/anki/out/qt/_aqt/forms/modelopts_qt5.py /home/user/anki/out/qt/_aqt/forms/modelopts_qt6.py /home/user/anki/out/qt/_aqt/forms/models_qt5.py /home/user/anki/out/qt/_aqt/forms/models_qt6.py /home/user/anki/out/qt/_aqt/forms/preferences_qt5.py /home/user/anki/out/qt/_aqt/forms/preferences_qt6.py /home/user/anki/out/qt/_aqt/forms/preview_qt5.py /home/user/anki/out/qt/_aqt/forms/preview_qt6.py /home/user/anki/out/qt/_aqt/forms/profiles_qt5.py /home/user/anki/out/qt/_aqt/forms/profiles_qt6.py /home/user/anki/out/qt/_aqt/forms/progress_qt5.py /home/user/anki/out/qt/_aqt/forms/progress_qt6.py /home/user/anki/out/qt/_aqt/forms/reposition_qt5.py /home/user/anki/out/qt/_aqt/forms/reposition_qt6.py /home/user/anki/out/qt/_aqt/forms/setgroup_qt5.py /home/user/anki/out/qt/_aqt/forms/setgroup_qt6.py /home/user/anki/out/qt/_aqt/forms/setlang_qt5.py /home/user/anki/out/qt/_aqt/forms/setlang_qt6.py /home/user/anki/out/qt/_aqt/forms/stats_qt5.py /home/user/anki/out/qt/_aqt/forms/stats_qt6.py /home/user/anki/out/qt/_aqt/forms/studydeck_qt5.py /home/user/anki/out/qt/_aqt/forms/studydeck_qt6.py /home/user/anki/out/qt/_aqt/forms/synclog_qt5.py /home/user/anki/out/qt/_aqt/forms/synclog_qt6.py /home/user/anki/out/qt/_aqt/forms/taglimit_qt5.py /home/user/anki/out/qt/_aqt/forms/taglimit_qt6.py /home/user/anki/out/qt/_aqt/forms/template_qt5.py /home/user/anki/out/qt/_aqt/forms/template_qt6.py /home/user/anki/out/qt/_aqt/forms/widgets_qt5.py /home/user/anki/out/qt/_aqt/forms/widgets_qt6.py /home/user/anki/out/qt/_aqt/forms/about_qt5.py 
/home/user/anki/out/rust/debug/runner run /home/user/anki/out/pyenv/bin/python qt/tools/build_ui.py /home/user/anki/out/qt/_aqt/forms/about_qt5.py
Command failed: 

Traceback (most recent call last):
  File "/home/user/anki/qt/tools/build_ui.py", line 12, in <module>
    from PyQt6.uic import compileUi
ModuleNotFoundError: No module named 'PyQt6'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/anki/qt/tools/build_ui.py", line 16, in <module>
    from PyQt5.uic import compileUi  # type: ignore
ModuleNotFoundError: No module named 'PyQt5'

[45/73; 1 active; 312.342s] pylib/rsbridge
ninja: build stopped: subcommand failed.

Build failed.
```

https://forums.ankiweb.net/t/error-compiling/27777

**Comment by krmanik** [comment]
https://github.com/ankitects/anki/blob/main/docs/linux.md#arm64-support

You need to install PyQt and PyQtWebEngine because on pypi .whl file not provided for arm64.
```
apt install python3-pyqt5 python3-pyqt5.qtwebengine python3-pip
```

**Comment by cantalupo555** [comment]
> https://github.com/ankitects/anki/blob/main/docs/linux.md#arm64-support
> 
> You need to install PyQt and PyQtWebEngine because on pypi .whl file not provided for arm64.
> 
> ```
> apt install python3-pyqt5 python3-pyqt5.qtwebengine python3-pip
> ```

Does the `pip install anki` command work?

```
cantalupo@orangepi5:~$ pip install anki
Defaulting to user installation because normal site-packages is not writeable
Collecting anki
  Downloading anki-2.1.60-cp39-abi3-manylinux_2_31_aarch64.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 2.9 MB/s eta 0:00:00
Collecting orjson
  Downloading orjson-3.8.8-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (260 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 260.7/260.7 KB 26.0 MB/s eta 0:00:00
Requirement already satisfied: distro in /usr/lib/python3/dist-packages (from anki) (1.7.0)
Collecting markdown
  Downloading Markdown-3.4.2-py3-none-any.whl (93 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.9/93.9 KB 15.7 MB/s eta 0:00:00
Collecting decorator
  Downloading decorator-5.1.1-py3-none-any.whl (9.1 kB)
Requirement already satisfied: requests[socks] in /usr/lib/python3/dist-packages (from anki) (2.25.1)
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.12.0-py3-none-any.whl (132 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.2/132.2 KB 21.3 MB/s eta 0:00:00
Collecting protobuf>=4.21
  Downloading protobuf-4.22.1-cp37-abi3-manylinux2014_aarch64.whl (301 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 301.2/301.2 KB 18.9 MB/s eta 0:00:00
Collecting soupsieve>1.2
  Downloading soupsieve-2.4-py3-none-any.whl (37 kB)
Collecting PySocks!=1.5.7,>=1.5.6
  Downloading PySocks-1.7.1-py3-none-any.whl (16 kB)
Installing collected packages: soupsieve, PySocks, protobuf, orjson, markdown, decorator, beautifulsoup4, anki
Successfully installed PySocks-1.7.1 anki-2.1.60 beautifulsoup4-4.12.0 decorator-5.1.1 markdown-3.4.2 orjson-3.8.8 protobuf-4.22.1 soupsieve-2.4
cantalupo@orangepi5:~$ anki
Command 'anki' not found, but can be installed with:
sudo apt install anki
cantalupo@orangepi5:~$
```

**Comment by Moerliy** [comment]
I have some issues with the build on my machine too. Is it possible to revive this repo and provide a Anki-arm-bin?
